included:
  - TestProject/TestProject/*

disabled_rules:
  # default rules
  - type_name
  # custom rules

opt_in_rules:
  # custom rules
  # - button_background_notifier
  # - button_shape_hstack_warning
  # - button_shape_vstack_warning
  # - navigation_title_length_warning
  # - ornament_system_warning
  - ornament_width_warning
