included:
  - Test\ Project/Test\ Project/*

disabled_rules:
  - type_name

opt_in_rules:
  - button_shape_vstack_warning
  - button_shape_hstack_warning

# custom_rules:
#   navigation_title_length:
#     included:
#       - ".*\\.swift"
#     name: "Navigation Title Length"
#     regex: '\.navigationTitle\(\"([^\"]{16,})\"\)'
#     message: "Navigation titles should not be longer than 15 characters."
#     severity: warning
